### PR TITLE
still call original error handlers

### PR DESCRIPTION
**Pull request by akatov**
e.g. a user may also be using ember-cli-sentry or any other (homebrewed) error handling solution

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Looks like the tests are failing, possibly due to a syntax error.

**Comment by danwenzel** [comment]
Because of line 27 (`console.error(error.stack);`), wouldn't many errors now show up twice in the console?

**Comment by akatov** [comment]
@danwenzel - I agree, but this is what this PR is about.
TBH I think that ember-new-relic shouldn't modify Ember.Logger.error at all. But this would be done in a different PR. @sir-dunxalot what do you think?

**Comment by sir-dunxalot** [comment]
If we can avoid modifying `Ember.Logger.error()` (or any of the other Ember methods) and have the errors logged to NR with the message and, stack then that would be preferred to the code we have now. The implementation should be testable to a degree. Whilst we can't programmatically test whether a NR account is receiving errors correctly, we should test as close as we can to that final call being sent to NR.

The original reason for modifying the Ember error methods was because not every Ember error was, by default, sent to NR unless we explicitly caught them like this. Meaning, if we do not modify the Ember error methods, we should add coverage for making sure every common Ember error *is* caught by NR's browser-side code.

**Comment by danwenzel** [comment]
@akatov - Perhaps you could add a 2nd argument to `handleError()` that is a boolean that determines if `console.error` gets called (default to `true`).  Then, if the oldError is successfully run in your `Ember.typeOf...` conditionals, set that boolean to false

**Comment by danwenzel** [comment]
@akatov - I tried to use this, and it wasn't working - at least for `Ember.onerror`

When this line hits:

`const _oldOnerror = Ember.onerror;`

...`Ember.onerror` is not yet defined.

**Comment by sir-dunxalot** [comment]
Looks like there are still some discussion points to resolve here. Also, since #15 was merged (to fix the formatting of error messages in the console), this PR will need changes in order to be merged.

Happy to help if I can.

**Comment by selbyk** [comment]
What's the status here?  Is the original issue resolved?

**Comment by GCheung55** [comment]
Any updates on this?

**Comment by sir-dunxalot** [comment]
No updates have been made to the PR. Given the discussion, I am not confident that this PR is ready to merge. If anyone would like to update this PR or make a PR to avoid overwriting `Ember.Logger` methods and `Ember.onerror` then that would be a great step forward.

**Comment by akatov** [comment]
I'm sorry, we've stopped using new-relic ourselves, so I will not be making any updates to this PR.

**Pull request closed without merging**
