### PR TITLE
Support New Relic Browser SPA Beta

### LINKED ISSUE #4: How will addon be affected by new New Relic SPA update
article here: http://www.cio.com/article/3092978/application-development/new-relic-adds-support-for-golang-spa-monitoring.html

what effects will this have on this addon?

---

**edit:** better article here: https://blog.newrelic.com/2016/07/12/spa-public-beta/

### PR DESCRIPTION
**Pull request by jeremy-w**
If the user has in their config.newRelic the value `spaMonitoring: true`, then we'll use the new tracking code. Otherwise, the old.

GOTCHA: If they explicitly set the `agent` config value, they'll want to delete it or update it, because the agents for the two services differ.

There were no tests in place for the addon code in `index.js` AFAICT, so I hacked together a crummy test runner using the `qunit` module in `node_tests/run.js`. To run, cd into there and `node run.js`. I did get it to exit with 0 on success and nonzero otherwise, so it could be incorporated into CI pretty readily if desired.

[fixes #4]

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Hey Jeremy, I am not ignoring this - was just away for the last couple of days. I will look through this and merge ASAP. On first glance this looks great!

**Comment by hakubo** [comment]
@sir-dunxalot can you define what ASAP is - I'd like to use that addon, and this is a blocker for us.

**Comment by sir-dunxalot** [comment]
This is on master branch now so you can install in your `package.json` as follows:

```
devDependencies: {
  "ember-new-relic": "sir-dunxalot/ember-new-relic"
}
```

I'll be able to make a release before the end of this weekend once I've QAed and linked up the test to Travis.

**Comment by sir-dunxalot** [comment]
This has been released as `0.3.0`. Thanks for the great work! It will be much appreciated by a lot of people. The tests are hooked up to Travis, which is another great addition of this PR.

**Comment by jeremy-w** [comment]
## Happy to hear it! Thanks for handling the Travis wiring.

Jeremy W. Sherman
http://jeremywsherman.com/

**Pull request merged**
